// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account_service.proto

package rs.raf.pds.faulttolerance.gRPC;

/**
 * Protobuf type {@code AccountRequest}
 */
public final class AccountRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AccountRequest)
    AccountRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AccountRequest.newBuilder() to construct.
  private AccountRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AccountRequest() {
    opType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AccountRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return rs.raf.pds.faulttolerance.gRPC.AccountServiceOuterClass.internal_static_AccountRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return rs.raf.pds.faulttolerance.gRPC.AccountServiceOuterClass.internal_static_AccountRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            rs.raf.pds.faulttolerance.gRPC.AccountRequest.class, rs.raf.pds.faulttolerance.gRPC.AccountRequest.Builder.class);
  }

  private int bitField0_;
  public static final int REQUEST_ID_FIELD_NUMBER = 1;
  private int requestId_ = 0;
  /**
   * <code>int32 request_id = 1;</code>
   * @return The requestId.
   */
  @java.lang.Override
  public int getRequestId() {
    return requestId_;
  }

  public static final int AMOUNT_FIELD_NUMBER = 2;
  private float amount_ = 0F;
  /**
   * <code>optional float amount = 2;</code>
   * @return Whether the amount field is set.
   */
  @java.lang.Override
  public boolean hasAmount() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional float amount = 2;</code>
   * @return The amount.
   */
  @java.lang.Override
  public float getAmount() {
    return amount_;
  }

  public static final int OP_TYPE_FIELD_NUMBER = 3;
  private int opType_ = 0;
  /**
   * <code>.AccountRequestType op_type = 3;</code>
   * @return The enum numeric value on the wire for opType.
   */
  @java.lang.Override public int getOpTypeValue() {
    return opType_;
  }
  /**
   * <code>.AccountRequestType op_type = 3;</code>
   * @return The opType.
   */
  @java.lang.Override public rs.raf.pds.faulttolerance.gRPC.AccountRequestType getOpType() {
    rs.raf.pds.faulttolerance.gRPC.AccountRequestType result = rs.raf.pds.faulttolerance.gRPC.AccountRequestType.forNumber(opType_);
    return result == null ? rs.raf.pds.faulttolerance.gRPC.AccountRequestType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (requestId_ != 0) {
      output.writeInt32(1, requestId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeFloat(2, amount_);
    }
    if (opType_ != rs.raf.pds.faulttolerance.gRPC.AccountRequestType.GET.getNumber()) {
      output.writeEnum(3, opType_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (requestId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, requestId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, amount_);
    }
    if (opType_ != rs.raf.pds.faulttolerance.gRPC.AccountRequestType.GET.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, opType_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof rs.raf.pds.faulttolerance.gRPC.AccountRequest)) {
      return super.equals(obj);
    }
    rs.raf.pds.faulttolerance.gRPC.AccountRequest other = (rs.raf.pds.faulttolerance.gRPC.AccountRequest) obj;

    if (getRequestId()
        != other.getRequestId()) return false;
    if (hasAmount() != other.hasAmount()) return false;
    if (hasAmount()) {
      if (java.lang.Float.floatToIntBits(getAmount())
          != java.lang.Float.floatToIntBits(
              other.getAmount())) return false;
    }
    if (opType_ != other.opType_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRequestId();
    if (hasAmount()) {
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAmount());
    }
    hash = (37 * hash) + OP_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + opType_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static rs.raf.pds.faulttolerance.gRPC.AccountRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.faulttolerance.gRPC.AccountRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.faulttolerance.gRPC.AccountRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.faulttolerance.gRPC.AccountRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.faulttolerance.gRPC.AccountRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.faulttolerance.gRPC.AccountRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.faulttolerance.gRPC.AccountRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.raf.pds.faulttolerance.gRPC.AccountRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static rs.raf.pds.faulttolerance.gRPC.AccountRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static rs.raf.pds.faulttolerance.gRPC.AccountRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static rs.raf.pds.faulttolerance.gRPC.AccountRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.raf.pds.faulttolerance.gRPC.AccountRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(rs.raf.pds.faulttolerance.gRPC.AccountRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AccountRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AccountRequest)
      rs.raf.pds.faulttolerance.gRPC.AccountRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rs.raf.pds.faulttolerance.gRPC.AccountServiceOuterClass.internal_static_AccountRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rs.raf.pds.faulttolerance.gRPC.AccountServiceOuterClass.internal_static_AccountRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rs.raf.pds.faulttolerance.gRPC.AccountRequest.class, rs.raf.pds.faulttolerance.gRPC.AccountRequest.Builder.class);
    }

    // Construct using rs.raf.pds.faulttolerance.gRPC.AccountRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      requestId_ = 0;
      amount_ = 0F;
      opType_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return rs.raf.pds.faulttolerance.gRPC.AccountServiceOuterClass.internal_static_AccountRequest_descriptor;
    }

    @java.lang.Override
    public rs.raf.pds.faulttolerance.gRPC.AccountRequest getDefaultInstanceForType() {
      return rs.raf.pds.faulttolerance.gRPC.AccountRequest.getDefaultInstance();
    }

    @java.lang.Override
    public rs.raf.pds.faulttolerance.gRPC.AccountRequest build() {
      rs.raf.pds.faulttolerance.gRPC.AccountRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public rs.raf.pds.faulttolerance.gRPC.AccountRequest buildPartial() {
      rs.raf.pds.faulttolerance.gRPC.AccountRequest result = new rs.raf.pds.faulttolerance.gRPC.AccountRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(rs.raf.pds.faulttolerance.gRPC.AccountRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.requestId_ = requestId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.amount_ = amount_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.opType_ = opType_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof rs.raf.pds.faulttolerance.gRPC.AccountRequest) {
        return mergeFrom((rs.raf.pds.faulttolerance.gRPC.AccountRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(rs.raf.pds.faulttolerance.gRPC.AccountRequest other) {
      if (other == rs.raf.pds.faulttolerance.gRPC.AccountRequest.getDefaultInstance()) return this;
      if (other.getRequestId() != 0) {
        setRequestId(other.getRequestId());
      }
      if (other.hasAmount()) {
        setAmount(other.getAmount());
      }
      if (other.opType_ != 0) {
        setOpTypeValue(other.getOpTypeValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              requestId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 21: {
              amount_ = input.readFloat();
              bitField0_ |= 0x00000002;
              break;
            } // case 21
            case 24: {
              opType_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int requestId_ ;
    /**
     * <code>int32 request_id = 1;</code>
     * @return The requestId.
     */
    @java.lang.Override
    public int getRequestId() {
      return requestId_;
    }
    /**
     * <code>int32 request_id = 1;</code>
     * @param value The requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestId(int value) {

      requestId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 request_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      requestId_ = 0;
      onChanged();
      return this;
    }

    private float amount_ ;
    /**
     * <code>optional float amount = 2;</code>
     * @return Whether the amount field is set.
     */
    @java.lang.Override
    public boolean hasAmount() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional float amount = 2;</code>
     * @return The amount.
     */
    @java.lang.Override
    public float getAmount() {
      return amount_;
    }
    /**
     * <code>optional float amount = 2;</code>
     * @param value The amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmount(float value) {

      amount_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional float amount = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAmount() {
      bitField0_ = (bitField0_ & ~0x00000002);
      amount_ = 0F;
      onChanged();
      return this;
    }

    private int opType_ = 0;
    /**
     * <code>.AccountRequestType op_type = 3;</code>
     * @return The enum numeric value on the wire for opType.
     */
    @java.lang.Override public int getOpTypeValue() {
      return opType_;
    }
    /**
     * <code>.AccountRequestType op_type = 3;</code>
     * @param value The enum numeric value on the wire for opType to set.
     * @return This builder for chaining.
     */
    public Builder setOpTypeValue(int value) {
      opType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.AccountRequestType op_type = 3;</code>
     * @return The opType.
     */
    @java.lang.Override
    public rs.raf.pds.faulttolerance.gRPC.AccountRequestType getOpType() {
      rs.raf.pds.faulttolerance.gRPC.AccountRequestType result = rs.raf.pds.faulttolerance.gRPC.AccountRequestType.forNumber(opType_);
      return result == null ? rs.raf.pds.faulttolerance.gRPC.AccountRequestType.UNRECOGNIZED : result;
    }
    /**
     * <code>.AccountRequestType op_type = 3;</code>
     * @param value The opType to set.
     * @return This builder for chaining.
     */
    public Builder setOpType(rs.raf.pds.faulttolerance.gRPC.AccountRequestType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      opType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.AccountRequestType op_type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOpType() {
      bitField0_ = (bitField0_ & ~0x00000004);
      opType_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AccountRequest)
  }

  // @@protoc_insertion_point(class_scope:AccountRequest)
  private static final rs.raf.pds.faulttolerance.gRPC.AccountRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new rs.raf.pds.faulttolerance.gRPC.AccountRequest();
  }

  public static rs.raf.pds.faulttolerance.gRPC.AccountRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AccountRequest>
      PARSER = new com.google.protobuf.AbstractParser<AccountRequest>() {
    @java.lang.Override
    public AccountRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AccountRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AccountRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public rs.raf.pds.faulttolerance.gRPC.AccountRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

