// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account_service.proto

package rs.raf.pds.faulttolerance.gRPC;

public interface AccountResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AccountResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.RequestStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.RequestStatus status = 1;</code>
   * @return The status.
   */
  rs.raf.pds.faulttolerance.gRPC.RequestStatus getStatus();

  /**
   * <code>int32 request_id = 2;</code>
   * @return The requestId.
   */
  int getRequestId();

  /**
   * <code>optional float balance = 3;</code>
   * @return Whether the balance field is set.
   */
  boolean hasBalance();
  /**
   * <code>optional float balance = 3;</code>
   * @return The balance.
   */
  float getBalance();

  /**
   * <code>optional string message = 4;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>optional string message = 4;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 4;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
