// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account_service.proto

package rs.raf.pds.faulttolerance.gRPC;

public final class AccountServiceOuterClass {
  private AccountServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AccountRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AccountRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AccountResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AccountResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LogEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LogEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LogResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LeaderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LeaderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LeaderInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LeaderInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025account_service.proto\"j\n\016AccountReques" +
      "t\022\022\n\nrequest_id\030\001 \001(\005\022\023\n\006amount\030\002 \001(\002H\000\210" +
      "\001\001\022$\n\007op_type\030\003 \001(\0162\023.AccountRequestType" +
      "B\t\n\007_amount\"\211\001\n\017AccountResponse\022\036\n\006statu" +
      "s\030\001 \001(\0162\016.RequestStatus\022\022\n\nrequest_id\030\002 " +
      "\001(\005\022\024\n\007balance\030\003 \001(\002H\000\210\001\001\022\024\n\007message\030\004 \001" +
      "(\tH\001\210\001\001B\n\n\010_balanceB\n\n\010_message\"6\n\010LogEn" +
      "try\022\024\n\014entryAtIndex\030\001 \001(\004\022\024\n\014logEntryDat" +
      "a\030\002 \001(\014\"o\n\013LogResponse\022\032\n\006status\030\001 \001(\0162\n" +
      ".LogStatus\022\024\n\014entryAtIndex\030\002 \001(\004\022\033\n\016last" +
      "EntryIndex\030\003 \001(\004H\000\210\001\001B\021\n\017_lastEntryIndex" +
      "\"\017\n\rLeaderRequest\"4\n\nLeaderInfo\022\020\n\010imLea" +
      "der\030\001 \001(\010\022\024\n\014hostnamePort\030\002 \001(\t*5\n\022Accou" +
      "ntRequestType\022\007\n\003GET\020\000\022\007\n\003ADD\020\001\022\r\n\tWITDR" +
      "AWAL\020\002*j\n\rRequestStatus\022\r\n\tSTATUS_OK\020\000\022\036" +
      "\n\032UPDATE_REJECTED_NOT_LEADER\020\001\022*\n&WITDRA" +
      "WAL_REJECT_NOT_SUFFICIENT_AMOUNT\020\002*?\n\tLo" +
      "gStatus\022\n\n\006LOG_OK\020\000\022\014\n\010IO_ERROR\020\001\022\030\n\024LOG" +
      "_HASNT_LAST_ENTRY\020\0022\202\002\n\016AccountService\0220" +
      "\n\tAddAmount\022\017.AccountRequest\032\020.AccountRe" +
      "sponse\"\000\0224\n\rWitdrawAmount\022\017.AccountReque" +
      "st\032\020.AccountResponse\"\000\0220\n\tGetAmount\022\017.Ac" +
      "countRequest\032\020.AccountResponse\"\000\022&\n\tAppe" +
      "ndLog\022\t.LogEntry\032\014.LogResponse\"\000\022.\n\rGetL" +
      "eaderInfo\022\016.LeaderRequest\032\013.LeaderInfo\"\000" +
      "B\"\n\036rs.raf.pds.faulttolerance.gRPCP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_AccountRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AccountRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AccountRequest_descriptor,
        new java.lang.String[] { "RequestId", "Amount", "OpType", "Amount", });
    internal_static_AccountResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AccountResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AccountResponse_descriptor,
        new java.lang.String[] { "Status", "RequestId", "Balance", "Message", "Balance", "Message", });
    internal_static_LogEntry_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_LogEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LogEntry_descriptor,
        new java.lang.String[] { "EntryAtIndex", "LogEntryData", });
    internal_static_LogResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_LogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LogResponse_descriptor,
        new java.lang.String[] { "Status", "EntryAtIndex", "LastEntryIndex", "LastEntryIndex", });
    internal_static_LeaderRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_LeaderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LeaderRequest_descriptor,
        new java.lang.String[] { });
    internal_static_LeaderInfo_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_LeaderInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LeaderInfo_descriptor,
        new java.lang.String[] { "ImLeader", "HostnamePort", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
