// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account_service.proto

package rs.raf.pds.faulttolerance.gRPC;

public interface LeaderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LeaderRequest)
    com.google.protobuf.MessageOrBuilder {
}
